Added OWS-ArcGIS pro doc
digitalearthafrica/deafrica-docs pull request #101
Opened 2023-02-13 13:15 UTC by mpho-sadiki

Added the instructions to connecting to the DE Africa Web Services for GIS using ArcGIS Pro. For each web service, the ArcGIS instructions were added after the relevant QGIS instructions.

2023-02-17 10:11 UTC, nanaboamah89 requested changes
At the left Panel, is it possible to have Submenus under
**Web Service for GIS**
     Web Map Service / Web Coverage Service
     QGIS
          Setting up WMS
           ..........
     ArcGIS Pro
            WMS-T layers
             ...........
     Troubleshooting

2023-02-28 08:21 UTC, mpho-sadiki commented
>

2023-02-28 11:24 UTC, nanaboamah89 approved these changes
Everything is fine from my side.

2023-03-01 06:33 UTC, lisarebelo approved these changes

2023-03-01 10:46 UTC, merged